packageExtensions:
  "@jest/types@*":
    dependencies:
      istanbul-lib-coverage: "*"
      istanbul-reports: "*"
      yargs: "*"
  "@types/glob-stream@*":
    dependencies:
      glob: "*"
  "@types/glob@*":
    dependencies:
      events: "*"
      minimatch: "*"
  "@types/gulp@*":
    dependencies:
      undertaker: "*"
      vinyl-fs: "*"
  "@types/istanbul-lib-report@*":
    dependencies:
      istanbul-lib-coverage: "*"
  "@types/istanbul-reports@*":
    dependencies:
      istanbul-lib-coverage: "*"
      istanbul-lib-report: "*"
  "@types/shelljs@*":
    dependencies:
      glob: "*"
  "@types/undertaker@*":
    dependencies:
      events: "*"
      undertaker-registry: "*"
  "@types/vinyl-fs@*":
    dependencies:
      events: "*"
      glob-stream: "*"
      vinyl: "*"
  "@types/yargs@*":
    dependencies:
      yargs-parser: "*"
  async-done@*:
    dependencies:
      events: "*"
  chokidar@*:
    dependencies:
      events: "*"
  debug@*:
    dependencies:
      supports-color: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.0.1.cjs

nodeLinker: pnp
