swagger: '2.0'
basePath: /
schemes:
  - http
info:
  title: тестовое апи коа
  version: 1.0.0
paths:
  /findBooks:
    get:
      description: test
      parameters:
        - in: query
          name: queryString
          type: string
      produces:
      - application/json
      responses:
        '200':
          description: A list of pets.
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: number
                name:
                  type: string
                publicationYear:
                  type: number
                author:
                  type: object
                  properties:
                    id:
                      type: number
                    firstName:
                      type: string
                    lastName:
                      type: string
                    middleName:
                      type: string
