swagger: '2.0'
basePath: /
schemes:
  - http
info:
  title: тестовое апи коа
  version: 1.0.0
paths:
  /findBooks:
    get:
      description: test
      parameters:
        - in: query
          name: queryString
          type: string
      produces:
      - application/json
      responses:
        '200':
          description: A list of pets.
          schema:
            type: array
