swagger: '2.0'
basePath: /
schemes:
  - http
info:
  title: тестовое апи коа
  version: 1.0.0
paths:
  /test:
    get:
      description: test
      produces:
      - application/json
      responses:
        '200':
          description: A list of pets.
          schema:
            type: string
